AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tranmere-Web-CDN

  Sam scripts for tranmere-web

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:

  cdn:
    Type: AWS::CloudFront::Distribution
    DependsOn: EdgeFunction
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          TargetOriginId: AmplifyMaster
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-response
              LambdaFunctionARN: !Ref EdgeFunction.Version
            - EventType: origin-request
              LambdaFunctionARN: !Ref EdgeRequestFunction.Version
        DefaultRootObject: index.html
        Enabled: true
        Aliases:
          - master.tranmere-web.com
        Origins:
          - DomainName: master.dj8vrlzimytqk.amplifyapp.com
            Id: AmplifyMaster
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:559251280975:certificate/113546fb-bd96-438c-9cba-98a208268206
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only

  EdgeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/edge/
      Handler: app.handler
      Runtime: nodejs12.x
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
      AutoPublishAlias: live

  EdgeRequestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/edge/
      Handler: request.handler
      Runtime: nodejs12.x
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
      AutoPublishAlias: live

  LambdaEdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowLambdaServiceToAssumeRole
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"

