AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tranmere-Web-Api

  Sam scripts for tranmere-web
Parameters:
  Email:
    Type: String
    Description: The email address to send contact to
  ESCluster:
    Type: String
    Description: The email address to send contact to
  ESUser:
    Type: String
    Description: The email address to send contact to
  ESPassword:
    Type: String
    Description: The email address to send contact to

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
  Api:
    Cors:
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  TranmereWebApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: TranmereWebApi Gateway
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://www.tranmere-web.com'"
        MaxAge: "'600'"
        AllowCredentials: True

  PlayerSearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/player-search/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ES_CLUSTER: !Ref 'ESCluster'
          ES_USER: !Ref 'ESUser'
          ES_PASSWORD: !Ref 'ESPassword'
      Events:
        PageRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /player-search
            RestApiId: !Ref TranmereWebApiGateway
            Method: get

  SearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/search/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ES_CLUSTER: !Ref 'ESCluster'
          ES_USER: !Ref 'ESUser'
          ES_PASSWORD: !Ref 'ESPassword'
      Events:
        PageRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            RestApiId: !Ref TranmereWebApiGateway
            Method: get

  PageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/page/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        PageRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /page/{pageName}
            RestApiId: !Ref TranmereWebApiGateway
            Method: get

  ScraperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/scraper/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        PageRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scraper/{season}/{id}
            RestApiId: !Ref TranmereWebApiGateway
            Method: get

  PlayerBuilderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/player-builder/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        PageRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /player-builder/{kit}/{hair}/{body}/{features}
            RestApiId: !Ref TranmereWebApiGateway
            Method: get

  ContactUsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/contact-us/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - AWSXrayWriteOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
      Environment:
        Variables:
          EMAIL_ADDRESS: !Ref 'Email'
      Events:
        ContactRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /contact-us
            RestApiId: !Ref TranmereWebApiGateway
            Method: post

  PlayerCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/crud/
      Handler: app.playerHandler
      Runtime: nodejs12.x
      Events:
        PlayerPostAPI:
          Type: Api
          Properties:
            Path: /api-player
            Method: POST
            RestApiId: !Ref TranmereWebApiGateway
        PlayerGetByNameAPI:
          Type: Api
          Properties:
            Path: /api-player/{name}
            Method: GET
            RestApiId: !Ref TranmereWebApiGateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayerTable

  MediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/media/
      Handler: app.mediaHandler
      Runtime: nodejs12.x
      Events:
        GetByCategoryAPI:
          Type: Api
          Properties:
            Path: /api-media/{category}
            Method: GET
            RestApiId: !Ref TranmereWebApiGateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MediaTable

  MediaBucket:
    Type: AWS::S3::Bucket
    BucketName: TranmereWebMedia

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/upload/
      Handler: app.mediaHandler
      Runtime: nodejs12.x
      Events:
        UploadMediaEvent:
          Type: S3
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            - BucketName: 'TranmereWebMedia'
        - DynamoDBCrudPolicy:
            TableName: !Ref MediaTable

  PlayerTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: PlayerTable
      AttributeDefinitions:
        - AttributeName: playerId
          AttributeType: S
      KeySchema:
        - AttributeName: playerId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MediaTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: MediaTable
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: category
          KeyType: HASH
        - AttributeName: id
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

Outputs:
  ContactUsFunction:
    Description: "Contact Us Lambda Function ARN"
    Value: !GetAtt ContactUsFunction.Arn
  ContactUsFunctionIamRole:
    Description: "Implicit IAM Role created for Contact Us function"
    Value: !GetAtt ContactUsFunctionRole.Arn
