AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tranmere-Web-Api

  Sam scripts for tranmere-web
Parameters:
  SCRAPESEASON:
    Type: String
    Description: The scrape season
  SCRAPEID:
    Type: String
    Description: The scrape season id
  SCRAPEURL:
    Type: String
    Description: The scrape URL
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600

Resources:

  TranmereWebCommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: 'Common code used by lambdas'
      ContentUri: src/common-layer/
      CompatibleRuntimes:
        - nodejs12.x

  ScraperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/scraper/
      Handler: app.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          SCRAPE_ID: !Ref 'SCRAPEID'
          SCRAPE_SEASON: !Ref 'SCRAPESEASON'
          SCRAPE_URL: !Ref 'SCRAPEURL'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebGames
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebGoals
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebApps
      Layers:
        - !Ref TranmereWebCommonLayer

  UpdateSummariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/updateJob/
      Handler: app.handler
      Runtime: nodejs12.x
      Tracing: Active
      Events:
        Daily:
          Type: Schedule
          Properties:
            Schedule: cron(40 21 * * ? *)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebPlayerSeasonSummary
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebGoals
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebApps
      Layers:
        - !Ref TranmereWebCommonLayer

  TranmereWebCSVUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tranmere-web-csv-uploads

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/upload/
      Handler: app.mediaHandler
      Runtime: nodejs12.x
      Events:
        UploadMediaEvent:
          Type: S3
          Properties:
            Bucket: !Ref TranmereWebCSVUploadBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: tranmere-web-csv-uploads
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebManagers
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebClubs
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebGames
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebGoals
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebApps
        - DynamoDBCrudPolicy:
            TableName: !Ref TranmereWebCompetitions
      Layers:
        - !Ref TranmereWebCommonLayer

  TranmereWebMediaTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebMediaSyncTable
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ByCategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: id
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL

  TranmereWebPlayerTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebPlayerTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ByNameIndex
          KeySchema:
            - AttributeName: name
              KeyType: HASH
            - AttributeName: id
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL

  TranmereWebManagers:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebManagers
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: id
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  TranmereWebClubs:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebClubs
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: id
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  TranmereWebCompetitions:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebCompetitions
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: id
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  TranmereWebStars:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebStarsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TranmereWebGames:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebGames
      AttributeDefinitions:
        - AttributeName: season
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: competition
          AttributeType: S
        - AttributeName: venue
          AttributeType: S
        - AttributeName: opposition
          AttributeType: S
        - AttributeName: static
          AttributeType: S
        - AttributeName: attendance
          AttributeType: N
      KeySchema:
        - AttributeName: season
          KeyType: HASH
        - AttributeName: date
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: AttendanceIndex
          KeySchema:
            - AttributeName: static
              KeyType: HASH
            - AttributeName: attendance
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: CompetitionIndex
          KeySchema:
            - AttributeName: competition
              KeyType: HASH
            - AttributeName: date
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: OppositionIndex
          KeySchema:
            - AttributeName: opposition
              KeyType: HASH
            - AttributeName: date
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: VenueIndex
          KeySchema:
            - AttributeName: venue
              KeyType: HASH
            - AttributeName: date
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL

  TranmereWebApps:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebAppsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: Season
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: Season
          KeyType: HASH
        - AttributeName: id
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ByPlayerIndex
          KeySchema:
            - AttributeName: Name
              KeyType: HASH
            - AttributeName: Date
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL

  TranmereWebPlayerSeasonSummary:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebPlayerSeasonSummaryTable
      AttributeDefinitions:
        - AttributeName: Player
          AttributeType: S
        - AttributeName: Season
          AttributeType: S
      KeySchema:
        - AttributeName: Season
          KeyType: HASH
        - AttributeName: Player
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ByPlayerIndex
          KeySchema:
            - AttributeName: Player
              KeyType: HASH
            - AttributeName: Season
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: true

  TranmereWebGoals:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TranmereWebGoalsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: Season
          AttributeType: S
      KeySchema:
        - AttributeName: Season
          KeyType: HASH
        - AttributeName: id
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
